Homescreensetup dev
RossyCodingClub/website_frontend pull request #10
Opened 2023-06-06 12:11 UTC by QuadAces

2023-06-06 12:26 UTC, Eisverygoodletter requested changes

2023-06-06 12:26 UTC, Eisverygoodletter commented on rccwebsite/src/app/blog-sidebar.tsx
> +	// return <p></p>;
Perhaps label this as a stub? (with TODO comments)

2023-06-06 12:26 UTC, Eisverygoodletter commented on rccwebsite/src/app/app.tsx
>  // eslint-disable-next-line @typescript-eslint/no-unused-vars
Is that comment necessary?

2023-06-06 12:26 UTC, Eisverygoodletter commented on rccwebsite/src/app/Components/Navbar.tsx
> +            //   contentLeft={
Clean up leftover comments

2023-06-06 13:33 UTC, txvvgnx approved these changes

2023-06-07 00:32 UTC, Eisverygoodletter approved these changes

2023-06-07 05:57 UTC, merged